version: '3.5'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    ports:
      - "2379:2379"

  milvus-minio:
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    container_name: milvus-minio
    command: server /minio_data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - minio_data:/minio_data
    ports:
      - "9000:9000"
      - "9001:9001"

  milvus:
    image: milvusdb/milvus:v2.4.3
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    depends_on:
      - milvus-etcd
      - milvus-minio
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - ETCD_ENDPOINTS=milvus-etcd:2379
      - MINIO_ADDRESS=milvus-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - DATA_PATH=/var/lib/milvus

volumes:
  etcd_data:
  minio_data:
  milvus_data:
  